name: Test Workflow

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check environment
        run: |
          echo "AWS_REGION: $AWS_REGION"
          echo "AZURE_REGION: $AZURE_REGION"
          echo "GITHUB_RUN_ID: $GITHUB_RUN_ID"